### ISSUE TITLE
GCC 7.2 constexpr compilation issues

### ISSUE THREAD

**Issue by magestik** [GPUOpen-Drivers/pal#1]
Hi,

I had some compilation issues while trying to compile this project on Fedora 27 :

> /mnt/workspace/vulkandriver/drivers/pal/src/util/math.cpp:73:1: error: 'const Util::Math::NBitFloatInfo{16, 10, 5, 15, 32768, 1023, 31744, 15, 15, -14, 1199562752, 947912704, ((Util::uint32)((((1 << (5 - 1)) - 1) - 127) << 23)), 13}' is not a constant expression
>  };
>  ^
> /mnt/workspace/vulkandriver/drivers/pal/src/util/math.cpp:91:1: error: 'const Util::Math::NBitFloatInfo{11, 6, 5, 0, 0, 63, 1984, 15, 15, -14, 1191698432, 947912704, ((Util::uint32)((((1 << (5 - 1)) - 1) - 127) << 23)), 17}' is not a constant expression
>  };
>  ^
> /mnt/workspace/vulkandriver/drivers/pal/src/util/math.cpp:109:1: error: 'const Util::Math::NBitFloatInfo{10, 5, 5, 0, 0, 31, 992, 15, 15, -14, 1191690240, 947912704, ((Util::uint32)((((1 << (5 - 1)) - 1) - 127) << 23)), 18}' is not a constant expression
>  };

I compiled using the instructions provided in the main repository (https://github.com/GPUOpen-Drivers/AMDVLK).

Thanks

----------------------------------

Compiler version :
```
c++ (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

CMake version :
```
cmake version 3.10.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by aejsmith** [comment]
Noticed this as well. Replacing constexpr with const works for me.

**Comment by shadiramadan** [comment]
Thanks for testing out our driver!  Officially we recommend you stick to GCC5 for now, however, we do have a fix in our pipeline for GCC7.2 that just didn’t make it to this first release.

Another fix (keeping constexpr) is to replace the offending biasDiff lines (71, 89, 107) with:

`    (((1U << (5 - 1)) - 1) - 127) << 23,                      // biasDiff`

We plan to include the fix in the next upcoming update.

Happy holidays!

**Comment by shadiramadan** [comment]
I made and approved a pull request on the dev branch fixing this issue. See commit 9f339fc4790bcea2c7aac136798fe5f953674117.

**Comment by jinjianrong** [comment]
The fix is merged to master
