### ISSUE TITLE
Compilation error on PAL_ASSERT_MSG

### ISSUE THREAD

**Issue by edrickhong** [GPUOpen-Drivers/pal#18]
On gcc 8.1.1 the current build in dev throws
AMDVLK/vulkandriver/drivers/pal/inc/util/palAssert.h:96:20: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]

In PAL_ASSERT_MSG()
changing if ((_expr) == false)

to either if (!(_expr)) or if ((_expr) == 0) should fix this

**Comment by JacobHeAMD** [comment]
It's an issue of xgl/icd/api/vk_memory.cpp:Memory::PalMemory, VK_ASSERT(m_pPalMemory[resourceIndex][index]) is not appropriate usage, "VK_ASSERT(m_pPalMemory[resourceIndex][index] != nullptr)" is correct.
Already fixed internally.

**Comment by JacobHeAMD** [comment]
It's fixed by the latest driver, please confirm it.
