### ISSUE TITLE
Is it possible to submit update patches individually rather than one giant patch includes many patches?

### ISSUE THREAD

**Issue by ardacoskunses** [GPUOpen-Drivers/pal#23]
Is it possible to submit update patches individually rather than one giant patch includes many patches?

It is very hard to read added features when they are not isolated.

**Comment by jinjianrong** [comment]
@ardacoskunses  PAL is a shared component for many of AMD's 3D and compute drivers, the open source version of PAL is sanitized from our internal version, this makes it difficult to keep the history of individual patches in the open source release. But it  is do in our consideration to gradually make the development  of amdvlk more open by restructuring our  process. We will  start to do this with LLPC first.

**Comment by ardacoskunses** [comment]
Thank you!
