### ISSUE TITLE
Possibly erroneous PAL_ASSERT

### ISSUE THREAD

**Issue by godlikepanos** [GPUOpen-Drivers/pal#24]
Hi,

When running AMDVLK driver on debug mode I get the following message:

AMD-PAL: Error: Assertion failed: pInfo->interpolatorCount >= 1 | Reason: Unknown (/some/path/drivers/pal/src/core/hw/gfxip/gfx6/gfx6PipelineChunkVsPs.cpp:124:EarlyInit)

I get this message on pipelines that are mainly used in shadowpasses. Those pipelines are not expected to have any varyings (I guess that's what you call interpolators). Maybe the assertion is incorrect.

**Comment by jinjianrong** [comment]
This assert might caught a misbehavior in LLPC. A fix will be available soon.

**Comment by godlikepanos** [comment]
Thanks. If you want a repro-case let me know.

**Comment by JacobHeAMD** [comment]
@godlikepanos , could you please help to check with the latest amdvlk to see if this issue is gone?

**Comment by godlikepanos** [comment]
Hi. Sorry for the late update. Haven't observed the issue latelly. Closing.
