### ISSUE TITLE
Swizzle questions

### ISSUE THREAD

**Issue by jpark37** [GPUOpen-Drivers/pal#40]
First, is this a good place for general questions about the PAL repo code?

On Gfx10, what is PipeBankXor exactly, and how important is it? I know it alters the swizzle pattern, but I'm wondering what would happen if I always used a ADDR2_COMPUTE_PIPEBANKXOR_INPUT::surfIndex of zero for example. Would parts of the hardware be underutilized? How much of a penalty might I be looking at?

For Gfx10Lib::HwlGetPreferredSurfaceSetting in the non-pow2 case, it looks like the swizzle precedence order for BC textures is D -> S -> R, and R -> D -> S for most other surfaces. What's the rationale there? How much worse might it be to use standard swizzle for BC textures when I could have used display?

**Comment by jpark37** [comment]
Also, is there a good place for questions that I don't want out in public?

**Comment by JaxLinAMD** [comment]
I guess @JacobHeAMD can answer your question

**Comment by qiaojbao** [comment]
PipeBankXor value is computed by addrlib, it must be compatible with HW.
Of course a pipe/bank xor setting of zero is always valid. In PAL code(Image::ComputePipeBankXor), you can find setting of zero for many situations.
You asked "How much of a penalty?", it is hard for me to give a exact here.
Hope helpful to you.
