### ISSUE TITLE
Use of select() file descriptor can exceed FD_SETSIZE

### ISSUE THREAD

**Issue by mgsegal** [GPUOpen-Drivers/pal#54]
The issue we ran into with select was that the file descriptor used in PAL was >= 1024 (FD_SETSIZE) which is the limit select fd_set will handle in glibc's implementation. Using poll doesn't have the same constraint and allows an application which already has many open file descriptors to work correctly with PAL.

**Comment by JakeMerdichAMD** [comment]
Fixed with #53
