### ISSUE TITLE
Driver failed to create swapchain if modesetting driver is being used.

### ISSUE THREAD

**Issue by davidmaoamd** [GPUOpen-Drivers/pal#6]
Any XCB/XLIB Vulkan application would fail to create swapchain if X is launched with mode setting driver but not amdgpu's ddx driver.

**Comment by davidmaoamd** [comment]
AMDVLK driver would query the busid of the master fd to ensure we are rendering with the same GPU on the client side.
However, unlike amdgpu ddx driver, mode setting driver did not call drmSetInterfaceVersion to set the unique string of the master fd, which makes the busid queried from kernel is empty.

We would like to raise the question to X to see if it is a proper behave to not calling drmSetInterfaceVersion on the newly opened fd.
At the same time, please stick with the amdgpu's ddx driver in the xserver side, which is our test vehicle.

**Comment by BNieuwenhuizen** [comment]
FYI this is the approach used by radv/intel:

https://cgit.freedesktop.org/mesa/mesa/tree/src/vulkan/wsi/wsi_common_x11.c#n100

Basically we just look at drmGetRenderDeviceNameFromFd for the fd used by the driver and a fd gotten over dri3 and see if those names are equal.

**Comment by davidmaoamd** [comment]
We do that as well for regular case.
But with mode setting driver, it returns fd with nodeType DRM_NODE_PRIMARY.
We cannot use drmGetRenderDeviceNameFromFd on Primary node type.

**Comment by jinjianrong** [comment]
The issue has been fixed in latest code
