### ISSUE TITLE
Shadowmap visual quality issues by a reduction of depth buffer precision

### ISSUE THREAD

**Issue by npcdoom** [GPUOpen-Drivers/pal#87]
In commit https://github.com/GPUOpen-Drivers/pal/commit/2483d46fa27c30502e497ea169ee53b142e9fa06 the depth buffer precision was lowered which causes a reduced visual quality in scenes with shadow maps.

This change was done before but was reverted in https://github.com/GPUOpen-Drivers/pal/pull/48/commits/02e0b6b86627bf47a7ac2b0579036742f4ae19cf

You can refer to the conversation on the commit to know more details and the previous issue #49

**Comment by qiaojbao** [comment]
This change is a regression, has reverted in internal.
