### ISSUE TITLE
Errors in lnxUuid.cpp fail the build of amdvlk-2022.Q3.2

### ISSUE THREAD

**Issue by v-fox** [GPUOpen-Drivers/pal#89]
Tried to make [a package for openSUSE](https://build.opensuse.org/package/show/home:X0F:HSF/amdvlk) and got this for both gcc-12 and clang-14:
```
[ 2332s] /home/abuild/rpmbuild/BUILD/amdvlk-2022.Q3.2/pal/src/util/lnx/lnxUuid.cpp:68:8: error: variable has incomplete type 'tm'
[ 2332s]     tm FixedPoint = {0, 0, 0, 1, 2, 2021};
[ 2332s]        ^
[ 2332s] /usr/include/wchar.h:83:8: note: forward declaration of 'tm'
[ 2332s] struct tm;
[ 2332s]        ^
[ 2332s] /home/abuild/rpmbuild/BUILD/amdvlk-2022.Q3.2/pal/src/util/lnx/lnxUuid.cpp:80:47: error: use of undeclared identifier 'CLOCK_MONOTONIC'
[ 2332s]     bool clockGettimeSuccess = (clock_gettime(CLOCK_MONOTONIC, &time) == 0);
[ 2332s]                                               ^
[ 2332s] /home/abuild/rpmbuild/BUILD/amdvlk-2022.Q3.2/pal/src/util/lnx/lnxUuid.cpp:90:47: error: use of undeclared identifier 'CLOCK_REALTIME'
[ 2332s]     bool clockGettimeSuccess = (clock_gettime(CLOCK_REALTIME, &time) == 0);
```

**Comment by Flakebi** [comment]
Interesting that it fails on openSUSE but compiles on most other systems (I checked for me locally, time.h is included indirectly through string.h).

Anyway, this should be easy to fix. I guess that adding an `#include <time.h>` at the top of `src/util/lnx/lnxUuid.cpp` makes it build?

**Comment by v-fox** [comment]
> Anyway, this should be easy to fix. I guess that adding an `#include <time.h>` at the top of `src/util/lnx/lnxUuid.cpp` makes it build?

Indeed, it got built with:
```patch
diff --git a/pal/src/util/lnx/lnxUuid.cpp b/pal/src/util/lnx/lnxUuid.cpp
index 603db2a..f8a2c8b 100644
--- a/pal/src/util/lnx/lnxUuid.cpp
+++ b/pal/src/util/lnx/lnxUuid.cpp
@@ -30,6 +30,7 @@
 
 #include <random>
 #include <unistd.h>
+#include <time.h>
 
 namespace Util
 {
```

**Comment by AngryPenguinPL** [comment]
Hi.
At OpenMandriva we hit same issue.
Few weeks ago we fixed it by include time.h as above.
https://github.com/OpenMandrivaAssociation/AMDVLK/commit/98f4d773fc7f196d97cac763788067629d7f1c4b

Issue first time appear with 2022.Q2.3 and in pal commit a40241a1e6f5970a9313efe686a79c0a429ea5eb

**Comment by Flakebi** [comment]
Thanks for confirming @v-fox! This is fixed internally now, so it should appear in the next release (or the one after that, not sure when the cut-off is/was).

**Comment by Flakebi** [comment]
@AngryPenguinPL, I’ve been glancing over the OpenMandrive build script and noticed that you package spvgen (which was also part of earlier official ubuntu amdvlk packages).
`spvgen.so` is only needed for the offline amdllpc shader compiler and not for the driver (actually not even more for that as it’s linked statically now). So, it doesn’t need to be part of the package, `amdvlk*.so` and `amd_icd*.json` are enough.
That also means you don’t necessarily need to fetch spvgen’s dependencies (glslang, spirv_tools, spirv_headers and spirv_cross).

Also, `-DBUILD_WAYLAND_SUPPORT=ON` has been the default since a while (though it doesn’t hurt to specify it explicitly) :)

**Comment by Flakebi** [comment]
The fix made it in into the [2022.Q3.4](https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2022.Q3.4) release, so I think this can be closed. (https://github.com/GPUOpen-Drivers/pal/blob/master/src/util/lnx/lnxUuid.cpp#L32)

**Comment by v-fox** [comment]
> The fix made it in into the [2022.Q3.4](https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2022.Q3.4) release, so I think this can be closed. (https://github.com/GPUOpen-Drivers/pal/blob/master/src/util/lnx/lnxUuid.cpp#L32)

Yep.
